[package]
name = "screenextend-discovery"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
rand.workspace = true
hostname.workspace = true
mdns-sd.workspace = true
screenextend-common.workspace = true
